version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "appsync-resolvers-compared"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gwi6n8wkaiqm"
s3_prefix = "appsync-resolvers-compared"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
