AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: appsync-resolvers-compared

Resources:
    LambdaResolvers:
       Type: AWS::Serverless::Application
       Properties:
          Location: 1-lambda-resolvers/template.yaml
          Parameters:
            ItemsTableName: !Ref ItemsTable
            ItemsTableArn: !GetAtt ItemsTable.Arn
    
    VTLResolvers:
       Type: AWS::Serverless::Application
       Properties:
          Location: 2-vtl-resolvers/template.yaml
          Parameters:
            ItemsTableName: !Ref ItemsTable
            ItemsTableArn: !GetAtt ItemsTable.Arn
    
    JavascriptPipelineResolvers:
       Type: AWS::Serverless::Application
       Properties:
          Location: 3-javascript-pipeline-resolvers/template.yaml
          Parameters:
            ItemsTableName: !Ref ItemsTable
            ItemsTableArn: !GetAtt ItemsTable.Arn                   
         
    ItemsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: !Sub ${AWS::StackName}-items-table
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
  ItemsTableName:
    Value: !Ref ItemsTable