AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31


Parameters:
  AppSyncApiId:
    Type: String
    Description: AppSync Api id
  ItemsTableName:
    Type: String
    Description: Items table name 
  ItemsTableArn:
    Type: String
    Description: Items table ARN

Globals:
  Function:
    Timeout: 30
    
Resources:
    AppSyncServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Principal:
                Service:
                  - appsync.amazonaws.com
        Path: /
        Policies:
          - PolicyName: AppSyncServiceRolePolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: !GetAtt GetItemFunction.Arn
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: !GetAtt CreateItemFunction.Arn
                  
    FunctionRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Principal:
                  Service:
                    - lambda.amazonaws.com
          Path: /
          Policies:
            - PolicyName: FunctionRolePolicy
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                    Resource: !Ref ItemsTableArn
    
    GetItemFunctionDataSource:
        Type: AWS::AppSync::DataSource
        Properties:
          ApiId: !Ref AppSyncApiId
          Name: GetItemFunctionLambdaResolver
          Type: AWS_LAMBDA
          ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
          LambdaConfig:
            LambdaFunctionArn: !GetAtt GetItemFunction.Arn
    
    CreateItemFunctionDataSource:
        Type: AWS::AppSync::DataSource
        Properties:
          ApiId: !Ref AppSyncApiId
          Name: CreateItemFunctionLambdaResolver
          Type: AWS_LAMBDA
          ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
          LambdaConfig:
            LambdaFunctionArn: !GetAtt CreateItemFunction.Arn        
    
    GetItemFunction:
        Type: AWS::Serverless::Function
        Metadata: # Manage esbuild properties
          BuildMethod: esbuild
          BuildProperties:
            Minify: true
            Target: "es2020"
            Sourcemap: true
            External: 
              - 'aws-sdk'
            EntryPoints: 
                - get-item.ts
        Properties:
          CodeUri: functions/
          Handler: app.handler
          Runtime: nodejs18.x
          Role: !GetAtt FunctionRole.Arn
          Environment:
            Variables:
                ITEMS_TABLE_NAME: !Ref ItemsTableName

    CreateItemFunction:
        Type: AWS::Serverless::Function
        Metadata: # Manage esbuild properties
          BuildMethod: esbuild
          BuildProperties:
            Minify: true
            Target: "es2020"
            Sourcemap: true
            External: 
              - 'aws-sdk'
            EntryPoints: 
                - create-item.ts
        Properties:
          CodeUri: functions
          Handler: app.handler
          Runtime: nodejs18.x
          Role: !GetAtt FunctionRole.Arn